# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(default='', max_length=60)),
                ('surname', models.CharField(default='', max_length=60)),
                ('gender', models.CharField(default='', max_length=10)),
                ('age_category', models.CharField(default='', max_length=10)),
                ('club', models.CharField(default='', max_length=80)),
                ('email', models.CharField(default='', max_length=180)),
                ('number', models.CharField(default='', max_length=40)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
