# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcgeneral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='surname',
            new_name='last_name',
        ),
    ]
