# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcgeneral', '0002_auto_20161116_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='tshirt_size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
