# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcgeneral', '0003_registration_tshirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='updated',
        ),
        migrations.AddField(
            model_name='registration',
            name='registered_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
