# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcgeneral', '0004_auto_20161117_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registered_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
